<h1>Liste des numéros<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Question" data-toc-modified-id="Question-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Question</a></span></li><li><span><a href="#Question" data-toc-modified-id="Question-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Question</a></span></li><li><span><a href="#Question" data-toc-modified-id="Question-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Question</a></span><ul class="toc-item"><li><span><a href="#autre-façon-de-faire" data-toc-modified-id="autre-façon-de-faire-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>autre façon de faire</a></span></li></ul></li><li><span><a href="#Question" data-toc-modified-id="Question-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Question</a></span></li><li><span><a href="#Question" data-toc-modified-id="Question-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Question</a></span></li><li><span><a href="#Question" data-toc-modified-id="Question-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Question</a></span></li><li><span><a href="#Question" data-toc-modified-id="Question-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Question</a></span></li><li><span><a href="#Question" data-toc-modified-id="Question-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Question</a></span></li><li><span><a href="#Question" data-toc-modified-id="Question-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Question</a></span></li><li><span><a href="#Question" data-toc-modified-id="Question-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Question</a></span></li><li><span><a href="#Question" data-toc-modified-id="Question-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Question</a></span></li><li><span><a href="#Question" data-toc-modified-id="Question-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Question</a></span></li><li><span><a href="#Questions--mathématiques-financière" data-toc-modified-id="Questions--mathématiques-financière-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>Questions  mathématiques financière</a></span><ul class="toc-item"><li><span><a href="#Q1" data-toc-modified-id="Q1-13.1"><span class="toc-item-num">13.1&nbsp;&nbsp;</span>Q1</a></span></li><li><span><a href="#Q2" data-toc-modified-id="Q2-13.2"><span class="toc-item-num">13.2&nbsp;&nbsp;</span>Q2</a></span></li><li><span><a href="#Q3" data-toc-modified-id="Q3-13.3"><span class="toc-item-num">13.3&nbsp;&nbsp;</span>Q3</a></span></li><li><span><a href="#Q4" data-toc-modified-id="Q4-13.4"><span class="toc-item-num">13.4&nbsp;&nbsp;</span>Q4</a></span></li><li><span><a href="#Q4" data-toc-modified-id="Q4-13.5"><span class="toc-item-num">13.5&nbsp;&nbsp;</span>Q4</a></span></li></ul></li><li><span><a href="#Question-probabilité" data-toc-modified-id="Question-probabilité-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>Question probabilité</a></span><ul class="toc-item"><li><span><a href="#Q1" data-toc-modified-id="Q1-14.1"><span class="toc-item-num">14.1&nbsp;&nbsp;</span>Q1</a></span></li><li><span><a href="#Q2" data-toc-modified-id="Q2-14.2"><span class="toc-item-num">14.2&nbsp;&nbsp;</span>Q2</a></span></li><li><span><a href="#Q3" data-toc-modified-id="Q3-14.3"><span class="toc-item-num">14.3&nbsp;&nbsp;</span>Q3</a></span></li></ul></li></ul></div>

# Question

Créer une matrice A au format 2X4 avec les valeurs suivantes: 1 2 3 4 5 6 7 8


In [93]:
1:8

[1] 1 2 3 4 5 6 7 8

In [101]:
A<- matrix(c(1:8), nrow = 2, ncol = 4)
A

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

Recréez cette matrice, mais cette fois les valeurs sont incrémentées par lignes

In [103]:
B<- matrix(c(1:8), nrow = 2, ncol = 4, byrow = T)
B

[,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 5    6    7    8

# Question

Créez une matrice carrée avec les valeurs du vecteur vec3 créée auparavant:


In [108]:
matrix(vec3, nrow = 5)

[,1] [,2] [,3] [,4] [,5]
[1,]  2   12   22   32   42  
[2,]  4   14   24   34   44  
[3,]  6   16   26   36   46  
[4,]  8   18   28   38   48  
[5,] 10   20   30   40   50

# Question

Créer une matrice identité 7X7

In [30]:
mat<-diag(7)
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 1    0    0    0    0    0    0   
[2,] 0    1    0    0    0    0    0   
[3,] 0    0    1    0    0    0    0   
[4,] 0    0    0    1    0    0    0   
[5,] 0    0    0    0    1    0    0   
[6,] 0    0    0    0    0    1    0   
[7,] 0    0    0    0    0    0    1

Afin des fins de calcul de réserves actuarielles, vous devez renverser (_reverse_) la diagonale de sorte où les 1 sont dans les cases (7,1), (6,2),...,(1,7)

In [31]:
apply(diag(7), 2, rev)

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 0    0    0    0    0    0    1   
[2,] 0    0    0    0    0    1    0   
[3,] 0    0    0    0    1    0    0   
[4,] 0    0    0    1    0    0    0   
[5,] 0    0    1    0    0    0    0   
[6,] 0    1    0    0    0    0    0   
[7,] 1    0    0    0    0    0    0

## autre façon de faire

In [32]:
mat <- mat[ nrow(mat):1, ]
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 0    0    0    0    0    0    1   
[2,] 0    0    0    0    0    1    0   
[3,] 0    0    0    0    1    0    0   
[4,] 0    0    0    1    0    0    0   
[5,] 0    0    1    0    0    0    0   
[6,] 0    1    0    0    0    0    0   
[7,] 1    0    0    0    0    0    0

# Question

À partir des données [suivantes](http://www.stat.gouv.qc.ca/statistiques/population-demographie/structure/mun_15000.htm), créez une matrice où vous avez la population des villes (Montréal, Québec, Laval, Gatineau) par ligne et les années 2013 à 2016 par colonnes

In [33]:
pop<-matrix(c(1718241,1735096,1746940,1767753,
              530474,533857,536013,538918,
              417325,421959,425481,429413,
              274180,276290,278050,281392), ncol=4, byrow = T)

In [34]:
pop

[,1]    [,2]    [,3]    [,4]   
[1,] 1718241 1735096 1746940 1767753
[2,]  530474  533857  536013  538918
[3,]  417325  421959  425481  429413
[4,]  274180  276290  278050  281392

In [35]:
rownames(pop)<-c("Montréal", "Québec", "Laval", "Gatineau")
colnames(pop)<-2013:2016

In [36]:
pop

2013    2014    2015    2016   
Montréal 1718241 1735096 1746940 1767753
Québec    530474  533857  536013  538918
Laval     417325  421959  425481  429413
Gatineau  274180  276290  278050  281392

On vous dit que l’arrondissement Hochelaga-Maisonneuve (situé à  Montréal) est devenu un quartier très aisé et veut maintenant avoir son indépendance. Aujourd'hui ce prestigieux quartier appelé HOMA, l'évolution de la population de ce quartier de 2013 à 2016 a été la suivante: 20000, 20500, 23000, 23800

Quelle aurait été la population de Montréal sans compter les habitants du pays très prospère pays HOMA

In [37]:
vec_HOMA<-c(20000, 20500, 23000, 23800)
HOMA<-matrix(vec_HOMA, ncol=4, )
rownames(HOMA)<-c("HOMA")
colnames(HOMA)<-2013:2016
HOMA

2013  2014  2015  2016 
HOMA 20000 20500 23000 23800

In [38]:
pop[1,]-vec_HOMA

2013    2014    2015    2016 
1698241 1714596 1723940 1743953

Reconstruisez la nouvelle matrice avec les nouvelles données de Montréal.

In [39]:
pop[1,]<-pop[1,]-vec_HOMA
pop

2013    2014    2015    2016   
Montréal 1698241 1714596 1723940 1743953
Québec    530474  533857  536013  538918
Laval     417325  421959  425481  429413
Gatineau  274180  276290  278050  281392

Ajouter les données de HOMA à la matrice modifiée|

In [173]:
rbind(pop,HOMA)

2013    2014    2015    2016   
Montréal 1698241 1714596 1723940 1743953
Québec    530474  533857  536013  538918
Laval     417325  421959  425481  429413
Gatineau  274180  276290  278050  281392
HOMA       20000   20500   23000   23800

# Question

Créer  deux  vecteurs  aléatoires  nommés  « x1 » et  « x2 »,  contenant  chacun  100  valeurs aléatoires compatibles 
1. avec une distribution de loi normale centrée réduite et 
2. avec une distribution de loi uniforme définie sur l’intervalle [0 ; 10]. 

In [42]:
x1<-rnorm(100)
x2<-runif(100, 0,10)

Créez une matrice 10X10 contient les valeur du vecteur x1 crée auparavant:

In [43]:
matNorm<-matrix(x1,nrow=10)

Calculez la moyenne de cette dernière et la variance de cette dernière

In [44]:
mean(matNorm)

[1] 0.01782549

In [45]:
(sd(matNorm))**2

[1] 0.823978

# Question

Créer un vecteur xx1 contenant un échantillon équiprobable de 4 variables à partir du vecteur x1 de la question précédente

In [46]:
xx1<-sample(x1, 4)
xx1

[1] -0.1639310  0.3002791  0.5964251 -0.4889228

À partir du vecteur xx1, créez un autre vecteur xx2 qui possède 1000 variables de l'échantillon xx1. La dernière variable possède une probabilité de 70% qu'elle soit tirée alors que les trois premières ont chacune 10% de chance qu'elle soit tirée.

In [47]:
xx2<-sample(xx1, 1000, replace = T, prob=c(.1,.1,.1,.7))

Donnez la fréquence de chacune des variables simulée


In [48]:
table(xx2)

xx2
-0.488922835294287 -0.163930968642975  0.300279118120242  0.596425059015276 
               705                 82                111                102 

# Question

On vous dit que les temps pour finir un demi-triathlon suivent une loi normale avec une moyenne (et les écarts types [ET])  pour les hommes et les femmes sont les suivantes:
* Pour les **hommes** nager 1.9 km en 40 minutes (ET=3), pédaler 90 km en 2:45 (ET=8), et courir 21.1 km en 2:05 (ET=10).
* Pour les **Femmes** nager 1.9 km en 50 minutes (ET=5), pédaler 90 km en 3:00 (ET=5), et courir 21.1 km en 2:15 (ET=12).


Créer les vecteurs {`swimH`, `bikeH`, `runH`, `swimF`, `bikeF`, `runF`} contenant le temps pour chacun des sports pour 1002 hommes et 1300 femmes, tirés aléatoirement selon les lois ci-dessus (on suppose que les trois sports sont indépendants même si en réalité ce n'est jamais vrai, car si on se blesse en vélo, on performe beaucoup moins en course).


In [49]:
set.seed(123)
n<-1002
swimH<-round(rnorm(n, mean = 40, sd = 3),2)
bikeH<-round(rnorm(n, mean = 165, sd = 8),2)
runH<-round(rnorm(n, mean = 125, sd = 8),2)

m<-1300
swimF<-round(rnorm(m, mean = 50, sd = 5),2)
bikeF<-round(rnorm(m, mean = 180, sd = 5),2)
runF<-round(rnorm(m, mean = 135, sd = 12),2)


Avec les vecteurs crée précedemment, construisez une matrice pour les hommes et une autre pour les femmes

In [50]:
resultatH<-matrix(c(swimH, bikeH, runH), ncol = 3)
colnames(resultatH)<-c("Swim", "Bike", "Run")
rownames(resultatH)<-paste("H",1:n,sep='')

In [51]:
head(resultatH)

Swim  Bike   Run   
H1 38.32 164.86 126.39
H2 39.31 163.94 120.08
H3 44.68 144.61 110.54
H4 40.21 173.32 119.85
H5 40.39 167.00 141.37
H6 45.15 184.33 120.51

In [52]:
tail(resultatH)

Swim  Bike   Run   
H997  43.21 169.29 123.80
H998  35.95 161.32 122.38
H999  38.43 160.91 113.41
H1000 39.25 166.90 119.42
H1001 37.01 160.67 145.79
H1002 36.88 174.75 124.70

In [53]:
resultatF<-matrix(c(swimF, bikeF, runF), ncol = 3)
colnames(resultatF)<-c("Swim", "Bike", "Run")
rownames(resultatF)<-paste("F",n+1:m,sep='')

In [54]:
head(resultatF)

Swim  Bike   Run   
F1003 54.57 180.26 117.59
F1004 49.08 184.04 130.86
F1005 53.05 175.30 115.72
F1006 49.74 180.20 149.05
F1007 56.82 170.01 131.69
F1008 47.48 180.69 132.66

In [55]:
tail(resultatF)

Swim  Bike   Run   
F2297 57.17 172.19 114.79
F2298 54.56 174.28 132.75
F2299 51.91 176.39 132.54
F2300 52.76 182.63 126.28
F2301 50.72 168.28 124.29
F2302 58.54 179.21 134.37

Créez une matrice qui contient les résultats des femmes ensuite et le résultat des hommes

In [292]:
résultat<-rbind(resultatH, resultatF)

In [293]:
head(résultat)

Swim  Bike   Run   
H1 40.54 171.39 135.25
H2 41.78 157.40 130.89
H3 46.27 168.04 131.96
H4 39.01 157.34 133.89
H5 36.20 160.56 118.65
H6 42.51 163.69 123.67

In [294]:
tail(résultat)

Swim  Bike   Run   
F2297 57.86 176.24 173.19
F2298 48.88 177.83 111.61
F2299 43.47 175.25 137.77
F2300 46.19 180.49 156.81
F2301 51.36 183.77 129.70
F2302 59.24 182.38 134.04

Quel est le numéro du dossard du participant/es qui a le meilleur temps en nage, et en combien de temps à accomplie cette discipline

In [273]:
min(résultat[, 1])

[1] 31.34

In [272]:
which(résultat[, 1]==min(résultat[, 1]))

H19 
 19

Quel est le numéro du dossard du participant/es qui a le meilleur temps en vélo, et en combien de temps à accomplie cette discipline

In [271]:
which(résultat[, 2]==min(résultat[, 2]))

H759 
 759

In [275]:
min(résultat[, 2])

[1] 142.31

Quel est le numéro du dossard du participant/es qui a le meilleur temps en course, et en combien de temps à accomplie cette discipline

In [276]:
which(résultat[, 3]==min(résultat[, 3]))

F1719 
 1719

In [277]:
min(résultat[, 3])

[1] 102.02

Quel a été le meilleur temps chez les femmes?

In [298]:
tempsF<-resultatF[, 1]+resultatF[, 2]+resultatF[, 3]

In [301]:
bestF<-min(tempsF)
bestF

[1] 322.77

Quel numéro de dossard?



In [302]:
which(tempsF==min(tempsF))

F1871 
  869

Qui a gagné la course et en combien de temps?

In [306]:
temps<-résultat[, 1]+résultat[, 2]+résultat[, 3]
gagnant<-min(temps)
gagnant
which(temps==min(temps))


[1] 292.15

H249 
 249

# Question

Créez un vecteur appelé _ann_ de qui représente les années de développement dans calcul d'annuité de 5 ans, qui donne le résultat suivant $\left\{1, \dots, 5\right\}$



In [42]:
ann<-1:5
ann

[1] 1 2 3 4 5

Créer un vecteur contenant les fameux facteurs d'actualisation $v^n$ qui servent à calculer la valeur présente d'une série de paiements $n=5$ avec un taux d'intérêt de 2.5% \begin{equation}\label{eq:v_n} v^n=\frac{1}{1+i} \end{equation}



In [44]:
i<-.025
v_n<-(1+i)**(-ann)
v_n

[1] 0.9756098 0.9518144 0.9285994 0.9059506 0.8838543

Calculer la valeur présente d'une annuité 5 ans avec qui 153.25$ par année


\begin{equation}\label{eq:a_n}
\begin{split}
PV &=a_n\\
&= v+v^2+ ,\dots, v^n\\
&=\sum_{j=1}^{n} v^{\text{ } j} 
\end{split}
\end{equation}

In [46]:
pmt<-153.25
sum(pmt*v_n)

[1] 711.9732

Reproduiser votre calcul avec la fonction suivante:
\begin{equation}\label{eq:a_nn}
\begin{split}
PV &=a_n\\
&= v+v^2+ ,\dots, v^n\\
&=\sum_{j=1}^{n} v^{\text{ } j} \\
&=\frac{1-v^n}{i}
\end{split}
\end{equation}
Lorsque le taux d'intérêt est constant d'une année à l'autre


In [ ]:
n<-5
i<-.025

In [60]:
vn<-(1+i)**-n
vn

[1] 0.8838543

In [63]:
PV<-(1-vn)/i
PV

[1] 4.645828

In [64]:
pmt*PV

[1] 711.9732

# Question

on se rappelle du taux _Effective rate of discount_

\begin{equation}\label{eq:d}
d_t=\frac{a(t)-a(t-1)}{a(t-1)}
\end{equation}


Le taux _discount_ se calcule avec la fonction suivante:

\begin{equation}\label{eq:d_i}
d=\frac{i}{1+i}=iv
\end{equation}


Soit un taux d'intérêt de 5%, quel sera alors de taux de _discount_ avec seulement 6 décimales

In [70]:
i<-.05
d<-i/(1+i)
round(d,6)

[1] 0.047619

# Question

Écrivez un code R pour créer la liste suivante :

In [349]:
(x <- list(ssd = c(256, 128, 512), machine = "Macbook Pro", best = TRUE))

$ssd
[1] 256 128 512

$machine
[1] "Macbook Pro"

$best
[1] TRUE

Ecrivez un code qui extrait les différente tailles du ssd **seulement**

In [350]:
x[[1]]

[1] 256 128 512

In [351]:
x$ssd

[1] 256 128 512

Extraire les étiquettes de la liste;

In [352]:
names(x)

[1] "ssd"     "machine" "best"

Extraire le 3e élément du premier élément de liste:

In [353]:
x[[1]][3]

[1] 512

Remplacer le dernier élément par le vecteur `T,F,T`

In [354]:
x[[3]]<-c(T,F,T)

In [355]:
x

$ssd
[1] 256 128 512

$machine
[1] "Macbook Pro"

$best
[1]  TRUE FALSE  TRUE

# Question

Soit le vecteur suivant:

In [362]:
x<-c(71,18,86,5,58,19,14,9,74,75,59,24,7,51,50,63,35,53,72,61)
x

[1] 71 18 86  5 58 19 14  9 74 75 59 24  7 51 50 63 35 53 72 61

Extraire le 10e élément du vecteur

In [363]:
x[10]

[1] 75

Extraire une partie du vecteur allant composé du 1er, 3e, ...., 19e élément

In [367]:
x[seq(from = 1, to = 19, by = 2)]

[1] 71 86 58 14 74 59  7 50 35 72

Extraire les éléments divisibles par deux (_even numbers_)

In [371]:
x[x%%2==0]

[1] 18 86 58 14 74 24 50 72

Extraire les éléments non divisibles par deux (_odd numbers_)

In [372]:
x[x%%2!=0]

[1] 71  5 19  9 75 59  7 51 63 35 53 61

Tous les éléments sauf 3e, 5e et 17e éléments

In [375]:
x[-c(3, 5, 17)]

[1] 71 18  5 19 14  9 74 75 59 24  7 51 50 63 53 72 61

Dans le vecteur `x`, combien d'éléments sont pairs et combien sont impairs

In [373]:
length(x[x%%2==0])

[1] 8

In [374]:
length(x[x%%2!=0])

[1] 12

# Question

Soit une matrice 12X7, 

In [56]:
x <- matrix(sample(1:100, 12*7), 12, 7)
x

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
 [1,] 97    55  61   20   86   87   35  
 [2,] 69    52  75    9   72   57   43  
 [3,] 36    23  30   14   10   78   59  
 [4,] 83   100  85   24   53   40    1  
 [5,] 84     4   6   33   66   91   71  
 [6,] 79    63  92   21   62   70   60  
 [7,] 38    25   3    8   74   81    5  
 [8,] 26    46  64   49   39   17   65  
 [9,] 58    68  11   47   54   45   50  
[10,] 95    82  96   29   16   88   37  
[11,] 89    93  34   15   90   32   41  
[12,]  2    94  27    7   76   51   12

extraire l'élément de la 5e ligne et 6e colonne

In [379]:
x[5,6]

[1] 45

Extraire tout le contenu de la 3e ligne et la 9 ligne

In [380]:
x[c(3,9),]

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 96   87   17   77   86    1   69  
[2,] 72    3   97   19   27   10   56

Extraire **tout** le contenu des colonnes impaires

In [385]:
x[,c(seq(from = 1, to = 7, by = 2))]

[,1] [,2] [,3] [,4]
 [1,] 40   95   100  16  
 [2,] 47   89    62  43  
 [3,] 96   17    86  69  
 [4,] 81   23    55  25  
 [5,] 63   68    88   2  
 [6,] 59   51    46  58  
 [7,] 31   80    83  39  
 [8,] 78   26    32  37  
 [9,] 72   97    27  56  
[10,] 98   60    90  64  
[11,] 30   41    73  49  
[12,] 76   48    14  13

# Questions  mathématiques financière

\begin{equation}\label{eq:relationship}
1+i =\Bigg(1+ \frac{i^{(m)}}{m} \Bigg)^m =(1-d)^{-1}=\Bigg(1- \frac{d^{(m)}}{m} \Bigg)^{-m} = e^{\delta}
\end{equation}

## Q1
En tenant compte de l'équation (\ref{eq:relationship}) Quelle est la valeur présente (arrondi à deux décimales) de 1000$ que vous aller recevoir dans 6 et 1/4 avec un taux _effective rate of discount_ de 9.27% par année

In [393]:
PV<-round(1000*(1-.0927)^6.25,2)
PV

[1] 544.43

## Q2
En tenant compte de l'équation (\ref{eq:relationship}) Quelle est la valeur accumulée (arrondi à deux décimales) de 1300$ que vous aller recevoir dans 10 et 1/2 avec un taux _effective rate of discount_ de 5.3286% par année

In [22]:
PV<-round(1300*(1-.053286)^-10.5,2)
PV

[1] 2310.18

## Q3
En tenant compte de l'équation (\ref{eq:relationship}) Quelle est la valeur accumulée (arrondi à deux décimales) de 50232$ que vous aller recevoir dans 17 ans avec un taux _nominal rate of interest_ de 13% par année convertible trimestriellement

In [396]:
FV=round(50232*(1+.13/4)^(17*4),2)
FV

[1] 442083.8

## Q4
En tenant compte de l'équation (\ref{eq:relationship}) Calculer la valeur présente de 82309$ à payer dans 8 ans avec un taux _nominal rate of discount_ de 6% par année composée mensuellement

In [397]:
FV<-round(82309*(1-(.06/12))^(12*8),2)
FV

[1] 50870.16

## Q4

Calculer la valeur présente d'une _annuity-immediate_ avec des paiements de 50$ chaque 6 mois pour 10 ans au taux d'intérêt nominal de 4% composé semi-annuellement:

In [399]:
pmts<-rep(50, 20)
pmts

[1] 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50

In [401]:
actu<-1:20
actu

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [406]:
sum(pmts*(1.02)^-actu)

[1] 817.5717

# Question probabilité

## Q1

Simuler une des valeurs tirées d'une distribution normale. Imaginez une population dont la taille moyenne est de 1.70m et un écart-type de 0.1m. En utilisant `rnorm` simulez 100 valeurs et sauvegardez cer dernières dans un objet de type vecteur appelé `taille`. 

**Note** Fixez votre seed à une valeur **123**

In [12]:
set.seed(123)
taille <- rnorm(n = 100, mean = 1.70, sd = .1)

Donnez un sommaire des statistiques descriptives du vecteur `taille`

In [13]:
summary(taille)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.469   1.651   1.706   1.709   1.769   1.919 

## Q2
Quelle est la probabilité qu'une personne soir plus petit que 1.90m ? Votre réponse arrondie à deux décimales

In [14]:
round(pnorm(1.90, mean = 1.70, sd = .1),2)

[1] 0.98

**Note**

Si on veut les formats en pourcentage, on peut utiliser la fonction `percent` du package `formattable`

In [7]:
install.packages("formattable")

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done


In [8]:
library(formattable)

In [15]:
percent(pnorm(1.90, mean = 1.70, sd = .1))

[1] 97.72%

Quelle est la probabilité que la taille d'une personne soit plus grande que 1.60 m

In [10]:
percent(1-pnorm(1.60, mean = 1.70, sd = .1))

[1] 84.13%

## Q3

Le temps d'attente (en minute) dans une clinique suit une loi exponentielle avec un taux de 1/50. Utiliser la fonction `rexp` afin de simuler les tempes d'attente pour 30 personnes dans cette clinique.

In [16]:
set.seed(123)
(patients <- rexp(rate = 1/50, n =30))

[1]  42.172863  28.830514  66.452743   1.578868   2.810549  15.825061
 [7]  15.711365   7.263340 136.311823   1.457672  50.241503  24.010736
[13]  14.050681  18.855892   9.414202  42.489306  78.160177  23.938021
[19]  29.546742 202.050586  42.157487  48.293561  74.263790  67.402224
[25]  58.426449  80.292617  74.837143  78.532627   1.588387  29.892485

Quelle est la probabilité qu'une personne attende moins que 10 minutes?

In [18]:
percent(pexp(q = 10,rate = 1/50))

[1] 18.13%

Supposons que la patience des gens atteint sa limite au bout de 60 minutes. Ça veut dire que s'ils attendent plus que 60 minutes, ils quittent la salle.

S'il y'a 100 personnes dans la salle, combien vont-ils quitter la salle?

In [21]:
percent(1 - pexp(q=60, rate =1/50))

[1] 30.12%