# Question

Dans R, la valeur de la variable du nombre $\pi$ est nommée « pi ». Afficher cette  valeur  à  l’écran avec une précision de 3  puis  de 5  décimales.  

In [23]:
pi

[1] 3.141593

In [24]:
round(pi,3)

[1] 3.142

In [25]:
round(pi, 5)

[1] 3.14159

# Question

Créer le vecteur « vec1 » contenant la suite des entiers de 1 à 12. Ajouter à la fin de ce vecteur les valeurs 16, 17, 18. 

In [26]:
vec1<-1:12
vec1

[1]  1  2  3  4  5  6  7  8  9 10 11 12

In [27]:
vec1<-c(vec1, 16:18)
vec1

[1]  1  2  3  4  5  6  7  8  9 10 11 12 16 17 18

# Question

Créer le vecteur « vec2 » contenant les valeurs suivantes : 0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0.

In [79]:
seq(0,5,.5)

[1] 0.0 0.5 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0

# Question

Créer le vecteur « vec3 » contenant tous les multiples de 2 compris entre 1 et 50. 

In [80]:
vec3<-seq(2,50, 2)
vec3

[1]  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50

# Question

Créer une matrice A au format 2X4 avec les valeurs suivantes: 1 2 3 4 5 6 7 8


In [93]:
1:8

[1] 1 2 3 4 5 6 7 8

In [101]:
A<- matrix(c(1:8), nrow = 2, ncol = 4)
A

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

Recréez cette matrice, mais cette fois les valeurs sont incrémentées par lignes

In [103]:
B<- matrix(c(1:8), nrow = 2, ncol = 4, byrow = T)
B

[,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 5    6    7    8

# Question

Créez une matrice carrée avec les valeurs du vecteur vec3 créée auparavant:


In [108]:
matrix(vec3, nrow = 5)

[,1] [,2] [,3] [,4] [,5]
[1,]  2   12   22   32   42  
[2,]  4   14   24   34   44  
[3,]  6   16   26   36   46  
[4,]  8   18   28   38   48  
[5,] 10   20   30   40   50

# Question

Créer une matrice identité 7X7

In [30]:
mat<-diag(7)
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 1    0    0    0    0    0    0   
[2,] 0    1    0    0    0    0    0   
[3,] 0    0    1    0    0    0    0   
[4,] 0    0    0    1    0    0    0   
[5,] 0    0    0    0    1    0    0   
[6,] 0    0    0    0    0    1    0   
[7,] 0    0    0    0    0    0    1

Afin des fins de calcul de réserves actuarielles, vous devez renverser (_reverse_) la diagonale de sorte où les 1 sont dans les cases (7,1), (6,2),...,(1,7)

In [31]:
apply(diag(7), 2, rev)

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 0    0    0    0    0    0    1   
[2,] 0    0    0    0    0    1    0   
[3,] 0    0    0    0    1    0    0   
[4,] 0    0    0    1    0    0    0   
[5,] 0    0    1    0    0    0    0   
[6,] 0    1    0    0    0    0    0   
[7,] 1    0    0    0    0    0    0

## autre façon de faire

In [32]:
mat <- mat[ nrow(mat):1, ]
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 0    0    0    0    0    0    1   
[2,] 0    0    0    0    0    1    0   
[3,] 0    0    0    0    1    0    0   
[4,] 0    0    0    1    0    0    0   
[5,] 0    0    1    0    0    0    0   
[6,] 0    1    0    0    0    0    0   
[7,] 1    0    0    0    0    0    0

# Question

À partir des données [suivantes](http://www.stat.gouv.qc.ca/statistiques/population-demographie/structure/mun_15000.htm), créez une matrice où vous avez la population des villes (Montréal, Québec, Laval, Gatineau) par ligne et les années 2013 à 2016 par colonnes

In [33]:
pop<-matrix(c(1718241,1735096,1746940,1767753,
              530474,533857,536013,538918,
              417325,421959,425481,429413,
              274180,276290,278050,281392), ncol=4, byrow = T)

In [34]:
pop

[,1]    [,2]    [,3]    [,4]   
[1,] 1718241 1735096 1746940 1767753
[2,]  530474  533857  536013  538918
[3,]  417325  421959  425481  429413
[4,]  274180  276290  278050  281392

In [35]:
rownames(pop)<-c("Montréal", "Québec", "Laval", "Gatineau")
colnames(pop)<-2013:2016

In [36]:
pop

2013    2014    2015    2016   
Montréal 1718241 1735096 1746940 1767753
Québec    530474  533857  536013  538918
Laval     417325  421959  425481  429413
Gatineau  274180  276290  278050  281392

On vous dit que l’arrondissement Hochelaga-Maisonneuve (situé à  Montréal) est devenu un quartier très aisé et veut maintenant avoir son indépendance. Aujourd'hui ce prestigieux quartier appelé HOMA, l'évolution de la population de ce quartier de 2013 à 2016 a été la suivante: 20000, 20500, 23000, 23800

Quelle aurait été la population de Montréal sans compter les habitants du pays très prospère pays HOMA

In [37]:
vec_HOMA<-c(20000, 20500, 23000, 23800)
HOMA<-matrix(vec_HOMA, ncol=4, )
rownames(HOMA)<-c("HOMA")
colnames(HOMA)<-2013:2016
HOMA

2013  2014  2015  2016 
HOMA 20000 20500 23000 23800

In [38]:
pop[1,]-vec_HOMA

2013    2014    2015    2016 
1698241 1714596 1723940 1743953

Reconstruisez la nouvelle matrice avec les nouvelles données de Montréal.

In [39]:
pop[1,]<-pop[1,]-vec_HOMA
pop

2013    2014    2015    2016   
Montréal 1698241 1714596 1723940 1743953
Québec    530474  533857  536013  538918
Laval     417325  421959  425481  429413
Gatineau  274180  276290  278050  281392

Ajouter les données de HOMA à la matrice modifiée|

In [173]:
rbind(pop,HOMA)

2013    2014    2015    2016   
Montréal 1698241 1714596 1723940 1743953
Québec    530474  533857  536013  538918
Laval     417325  421959  425481  429413
Gatineau  274180  276290  278050  281392
HOMA       20000   20500   23000   23800